### ISSUE TITLE
Ipad Issues

### ISSUE THREAD

**Issue by nelzaatari** [Busta117/SBInstagram#10]
Good day,

we have some issues running it on IPad, 

- the UISegmentedController is not aligned properly when the IPad is rotated landscape

![ios simulator screen shot dec 2 2014 9 22 50 am](https://cloud.githubusercontent.com/assets/8324796/5258762/74e37e86-7a06-11e4-9ad2-776d2b9ccc31.png)

- ln Listview mode , the video is being played in a smaller frame size

![ios simulator screen shot dec 2 2014 9 22 32 am](https://cloud.githubusercontent.com/assets/8324796/5258810/6d5ca7b8-7a07-11e4-9d67-c34ced8f387e.png)

- ln collectionview mode , the video is being pushed with a cut from below

![ios simulator screen shot dec 2 2014 9 22 48 am](https://cloud.githubusercontent.com/assets/8324796/5258831/bd568acc-7a07-11e4-99fb-2142987d5098.png)

appreciate your usual support

**Comment by Busta117** [comment]
hello, sorry for the late response

this is already fixed in the version 2.2 released today, check it
